[project]
protostar-version = "0.8.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
    "src",
    "tests",
]

[contracts]
ERC3525MintableBurnable = [
    "./src/carbonable/erc3525/presets/ERC3525MintableBurnable.cairo",
]
