[project]
protostar-version = "0.7.0"
libs_path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
    "src",
    "tests",
]

[contracts]
ERC3525Example = [
    "./src/carbonable/erc3525/ERC3525Example.cairo",
]
